import type { DependencyRule } from "../types.js";

export const dependencyRules: DependencyRule[] = [
  {
    id: "dep-001",
    severity: "critical",
    triggerKeywords: ["全熱交換器", "全熱交換"],
    requiredKeywords: ["洗洞", "鑽孔"],
    searchInCategories: ["masonry", "hvac", "plumbing"],
    title: "全熱交換器缺少洗洞/鑽孔",
    why: "全熱交換器需要進排氣穿牆孔（通常2-4個），未施作洗洞將無法安裝",
    suggestion: "請新增洗洞/鑽孔工項，通常需要2-4個穿牆孔",
  },
  {
    id: "dep-002",
    severity: "critical",
    triggerKeywords: ["浴室拆除", "衛浴拆除", "浴室翻新", "浴室全拆"],
    requiredKeywords: ["防水", "防水工程"],
    searchInCategories: ["waterproofing"],
    title: "浴室拆除/翻新缺少防水工程",
    why: "浴室翻新必做防水，否則漏水到樓下需賠償並重做，損失極大",
    suggestion: "請新增浴室防水工程，含一底二塗及試水測試",
  },
  {
    id: "dep-003",
    severity: "critical",
    triggerKeywords: ["拆除磁磚", "地磚拆除", "拆除地磚", "磁磚拆除"],
    requiredKeywords: ["整平", "地面整平", "打底"],
    searchInCategories: ["masonry"],
    title: "地磚拆除缺少地面整平",
    why: "拆除地磚後地面高低差必須整平處理，否則後續地板或磁磚鋪設品質不佳",
    suggestion: "請新增地面整平工項",
  },
  {
    id: "dep-004",
    severity: "critical",
    triggerKeywords: ["砌磚牆", "砌磚", "新砌牆"],
    requiredKeywords: ["粉光"],
    searchInCategories: ["masonry"],
    title: "砌磚牆缺少粉光",
    why: "新砌磚牆面必須粉光才能上漆或貼壁紙，裸磚無法居住",
    suggestion: "請新增粉光工項",
  },
  {
    id: "dep-005",
    severity: "critical",
    triggerKeywords: ["拆除"],
    requiredKeywords: ["垃圾清運", "清運", "廢棄物清運"],
    searchInCategories: ["demolition", "cleaning", "transport"],
    title: "拆除工程缺少垃圾清運",
    why: "垃圾清運是最常被漏報的項目，拆除廢料堆積將無法繼續施工",
    suggestion: "請新增垃圾清運工項，全室拆除約每10坪2車",
  },
  {
    id: "dep-006",
    severity: "warning",
    triggerKeywords: ["木地板", "超耐磨", "海島型"],
    requiredKeywords: ["自平水泥", "自平", "整平"],
    searchInCategories: ["masonry"],
    title: "木地板缺少自平水泥",
    why: "木地板鋪設前需精密整平，否則地板踩踏有聲、接縫不平",
    suggestion: "建議新增自平水泥工項",
  },
  {
    id: "dep-007",
    severity: "critical",
    triggerKeywords: ["浴缸拆除"],
    requiredKeywords: ["防水", "防水工程"],
    searchInCategories: ["waterproofing"],
    title: "浴缸拆除缺少防水工程",
    why: "浴缸拆除後底座區域防水層已被破壞，必須重做防水",
    suggestion: "請新增防水工程，含底座區域防水及試水測試",
  },
  {
    id: "dep-008",
    severity: "critical",
    triggerKeywords: ["廚具拆除", "廚房拆除", "廚房全拆"],
    requiredKeywords: ["瓦斯管", "瓦斯封"],
    searchInCategories: ["plumbing"],
    title: "廚具拆除缺少瓦斯管封閉",
    why: "廚具拆除後瓦斯管若未封閉，有瓦斯外洩危險，屬安全問題",
    suggestion: "請新增瓦斯管封閉工項",
  },
  {
    id: "dep-009",
    severity: "critical",
    triggerKeywords: ["天花板拆除"],
    requiredKeywords: ["天花板", "平釘天花", "造型天花"],
    searchInCategories: ["carpentry"],
    title: "天花板拆除缺少天花板重做",
    why: "拆除天花板後不可能不做處理（除非刻意保留裸天花工業風格）",
    suggestion: "請新增天花板工程（平釘或造型天花板）",
  },
  {
    id: "dep-010",
    severity: "warning",
    triggerKeywords: ["隔間牆拆除", "隔間拆除"],
    requiredKeywords: ["結構", "結構確認", "結構補強"],
    title: "隔間牆拆除缺少結構確認",
    why: "需確認拆除的是否為結構牆，結構牆不可拆除，誤拆可能造成建築安全問題",
    suggestion: "請確認拆除牆面是否為結構牆，建議由結構技師確認",
  },
  {
    id: "dep-011",
    severity: "critical",
    triggerKeywords: ["馬桶移位"],
    requiredKeywords: ["墊高", "地板墊高", "架高"],
    searchInCategories: ["masonry", "plumbing", "flooring"],
    title: "馬桶移位缺少墊高地板",
    why: "馬桶移位需要糞管配管，排汙管需要洩水坡度，因此需墊高地板",
    suggestion: "請新增地板墊高工項",
  },
  {
    id: "dep-012",
    severity: "warning",
    triggerKeywords: ["全室拆除", "全面拆除"],
    requiredKeywords: ["保護工程", "電梯保護", "公共區域保護"],
    searchInCategories: ["protection"],
    title: "全室拆除缺少保護工程",
    why: "全室拆除工程量大，搬運廢料容易損壞公設，大樓施工幾乎必備保護工程",
    suggestion: "請新增保護工程（電梯保護+公共區域保護）",
  },
  {
    id: "dep-013",
    severity: "critical",
    triggerKeywords: ["空調安裝", "冷氣安裝", "冷氣"],
    requiredKeywords: ["排水管", "排水器", "冷凝水"],
    searchInCategories: ["hvac", "plumbing"],
    title: "空調安裝缺少排水管",
    why: "冷氣運作產生冷凝水，未配排水管會導致漏水",
    suggestion: "請新增冷氣排水管或排水器工項",
  },
  {
    id: "dep-014",
    severity: "info",
    triggerKeywords: ["系統櫃", "衣櫃", "書櫃"],
    requiredKeywords: ["丈量", "淨高", "確認淨高"],
    searchInCategories: ["cabinet"],
    title: "系統櫃提醒：需確認淨高",
    why: "系統櫃需在天花板完成後才丈量確認淨高，淨高確定才能下料生產",
    suggestion: "請確認系統櫃丈量時程安排在天花板完工後",
  },
  {
    id: "dep-015",
    severity: "warning",
    triggerKeywords: ["貼磁磚", "貼地磚", "貼壁磚"],
    requiredKeywords: ["收邊條", "收邊", "矽利康"],
    searchInCategories: ["masonry", "flooring"],
    title: "貼磁磚缺少收邊條",
    why: "磁磚與其他材質交接處需收邊處理，否則影響美觀及安全",
    suggestion: "請新增收邊條或矽利康收邊工項",
  },
  // ── 餐廳專用規則 ──
  {
    id: "dep-rest-001",
    severity: "critical",
    triggerKeywords: ["廚房", "中島", "爐台", "炒台"],
    requiredKeywords: ["排油煙", "油煙機", "排煙", "抽油煙"],
    searchInCategories: ["hvac", "plumbing"],
    title: "餐廳廚房缺少排油煙系統",
    why: "商業廚房排油煙不足會導致衛生局稽查不過，營業許可被擋，且油煙影響用餐區",
    suggestion: "請新增商業級排油煙機及排煙管道工項",
  },
  {
    id: "dep-rest-002",
    severity: "critical",
    triggerKeywords: ["廚房", "中島", "爐台", "水槽"],
    requiredKeywords: ["截油槽", "油脂截留器", "油水分離"],
    searchInCategories: ["plumbing"],
    title: "餐廳廚房缺少截油槽",
    why: "商業餐廳排水依法須設截油槽（油脂截留器），未設置將被環保局開罰且堵塞公共管線",
    suggestion: "請新增截油槽（油脂截留器）工項",
  },
  {
    id: "dep-rest-003",
    severity: "warning",
    triggerKeywords: ["廚房", "廚房地板"],
    requiredKeywords: ["防滑", "止滑", "防水"],
    searchInCategories: ["flooring", "waterproofing"],
    title: "餐廳廚房缺少防滑/防水處理",
    why: "商業廚房地面全天濕滑，未做防滑處理有工傷風險，且需全地坪防水避免漏水至樓下",
    suggestion: "建議廚房地坪採用防滑磁磚並施作全區防水",
  },
  // ── 商業空間專用規則 ──
  {
    id: "dep-comm-001",
    severity: "critical",
    triggerKeywords: ["裝修", "隔間", "天花板", "木作"],
    requiredKeywords: ["消防申報", "消防", "消防圖審"],
    searchInCategories: ["other"],
    title: "商業空間缺少消防申報",
    why: "商業空間裝修依法須向消防局申報，未申報直接罰款，且後續營業登記會被擋",
    suggestion: "請新增消防圖審及申報費用工項",
  },
  {
    id: "dep-comm-002",
    severity: "warning",
    triggerKeywords: ["裝修", "入口", "大門"],
    requiredKeywords: ["無障礙", "斜坡", "殘障"],
    searchInCategories: ["masonry", "other"],
    title: "商業空間建議評估無障礙設施",
    why: "公共營業空間依建築法規可能需設置無障礙設施，未設置可能影響使用執照",
    suggestion: "建議評估是否需新增無障礙坡道/廁所等設施",
  },
  // ── 專櫃專用規則 ──
  {
    id: "dep-retail-001",
    severity: "critical",
    triggerKeywords: ["木作", "櫃體", "展示櫃", "層板"],
    requiredKeywords: ["防火建材", "耐燃", "防焰"],
    searchInCategories: ["carpentry", "other"],
    title: "專櫃木作缺少防火建材",
    why: "百貨公司消防規範要求所有裝修材料須達耐燃等級，一般木作板材不符合，驗收會被退件",
    suggestion: "請確認所有木作板材使用耐燃一級或二級建材，並準備材料證明",
  },
  {
    id: "dep-retail-002",
    severity: "warning",
    triggerKeywords: ["裝修", "施工"],
    requiredKeywords: ["夜間施工", "施工時段"],
    searchInCategories: ["other"],
    title: "專櫃施工需確認百貨施工時段",
    why: "百貨施工通常限制在閉店後夜間進行，夜間施工人工成本加 30-50%，嚴重影響報價",
    suggestion: "請確認百貨施工時段限制，並將夜間加價納入報價",
  },
  // ── 毛胚屋專用規則 ──
  {
    id: "dep-raw-001",
    severity: "critical",
    triggerKeywords: ["裝修", "油漆", "木作", "地板"],
    requiredKeywords: ["整平", "地面整平", "打底", "粉光"],
    searchInCategories: ["masonry"],
    title: "毛胚屋缺少全室整平/粉光",
    why: "毛胚屋牆面地面均為粗胚狀態，未經整平粉光無法進行任何後續裝修（油漆、貼磚、鋪地板皆不可）",
    suggestion: "請新增全室牆面粉光及地面整平工項",
  },
  {
    id: "dep-raw-002",
    severity: "critical",
    triggerKeywords: ["裝修", "木作", "地板"],
    requiredKeywords: ["油漆", "批土", "底漆"],
    searchInCategories: ["painting"],
    title: "毛胚屋缺少全室油漆",
    why: "毛胚牆面粉光後仍需批土打底及油漆才能完成，這是毛胚屋最大量的基礎工程之一",
    suggestion: "請新增全室批土 + 底漆 + 面漆工項",
  },
  // ── 辦公大樓專用規則 ──
  {
    id: "dep-office-001",
    severity: "warning",
    triggerKeywords: ["隔間", "裝修", "辦公"],
    requiredKeywords: ["弱電", "網路", "資訊"],
    searchInCategories: ["plumbing", "other"],
    title: "辦公空間缺少弱電規劃",
    why: "辦公空間弱電需求高（網路/WiFi AP/投影機/電視/傳真/門禁），未規劃完整清單會導致追加",
    suggestion: "請依座位數及設備需求，列出完整弱電清單（網路點位、WiFi AP、投影、門禁等）",
  },
  {
    id: "dep-office-002",
    severity: "warning",
    triggerKeywords: ["電腦", "伺服器", "機房", "UPS"],
    requiredKeywords: ["UPS", "不斷電"],
    searchInCategories: ["plumbing", "other"],
    title: "辦公空間建議評估 UPS 獨立迴路",
    why: "UPS 設備耗電量大，通常需要至少 2 組獨立迴路，與一般照明/空調迴路分開避免跳電",
    suggestion: "請確認 UPS 迴路需求（通常至少 2 迴），並與一般迴路分開配置",
  },
  {
    id: "dep-office-003",
    severity: "warning",
    triggerKeywords: ["裝修", "施工"],
    requiredKeywords: ["管委會", "施工申請", "大樓規範"],
    searchInCategories: ["other"],
    title: "辦公大樓需確認管委會施工規範",
    why: "商辦大樓施工需向管委會申請，通常有施工時段限制、貨梯使用規範、保證金等要求",
    suggestion: "請確認大樓管委會施工申請流程及相關費用",
  },
];
