import type { DependencyRule } from "../types.js";

export const dependencyRules: DependencyRule[] = [
  {
    id: "dep-001",
    severity: "critical",
    triggerKeywords: ["全熱交換器", "全熱交換"],
    requiredKeywords: ["洗洞", "鑽孔"],
    searchInCategories: ["masonry", "hvac", "plumbing"],
    title: "全熱交換器缺少洗洞/鑽孔",
    why: "全熱交換器需要進排氣穿牆孔（通常2-4個），未施作洗洞將無法安裝",
    suggestion: "請新增洗洞/鑽孔工項，通常需要2-4個穿牆孔",
  },
  {
    id: "dep-002",
    severity: "critical",
    triggerKeywords: ["浴室拆除", "衛浴拆除", "浴室翻新", "浴室全拆"],
    requiredKeywords: ["防水", "防水工程"],
    searchInCategories: ["waterproofing"],
    title: "浴室拆除/翻新缺少防水工程",
    why: "浴室翻新必做防水，否則漏水到樓下需賠償並重做，損失極大",
    suggestion: "請新增浴室防水工程，含一底二塗及試水測試",
  },
  {
    id: "dep-003",
    severity: "critical",
    triggerKeywords: ["拆除磁磚", "地磚拆除", "拆除地磚", "磁磚拆除"],
    requiredKeywords: ["整平", "地面整平", "打底"],
    searchInCategories: ["masonry"],
    title: "地磚拆除缺少地面整平",
    why: "拆除地磚後地面高低差必須整平處理，否則後續地板或磁磚鋪設品質不佳",
    suggestion: "請新增地面整平工項",
  },
  {
    id: "dep-004",
    severity: "critical",
    triggerKeywords: ["砌磚牆", "砌磚", "新砌牆"],
    requiredKeywords: ["粉光"],
    searchInCategories: ["masonry"],
    title: "砌磚牆缺少粉光",
    why: "新砌磚牆面必須粉光才能上漆或貼壁紙，裸磚無法居住",
    suggestion: "請新增粉光工項",
  },
  {
    id: "dep-005",
    severity: "critical",
    triggerKeywords: ["拆除"],
    requiredKeywords: ["垃圾清運", "清運", "廢棄物清運"],
    searchInCategories: ["demolition", "cleaning", "transport"],
    title: "拆除工程缺少垃圾清運",
    why: "垃圾清運是最常被漏報的項目，拆除廢料堆積將無法繼續施工",
    suggestion: "請新增垃圾清運工項，全室拆除約每10坪2車",
  },
  {
    id: "dep-006",
    severity: "warning",
    triggerKeywords: ["木地板", "超耐磨", "海島型"],
    requiredKeywords: ["自平水泥", "自平", "整平"],
    searchInCategories: ["masonry"],
    title: "木地板缺少自平水泥",
    why: "木地板鋪設前需精密整平，否則地板踩踏有聲、接縫不平",
    suggestion: "建議新增自平水泥工項",
  },
  {
    id: "dep-007",
    severity: "critical",
    triggerKeywords: ["浴缸拆除"],
    requiredKeywords: ["防水", "防水工程"],
    searchInCategories: ["waterproofing"],
    title: "浴缸拆除缺少防水工程",
    why: "浴缸拆除後底座區域防水層已被破壞，必須重做防水",
    suggestion: "請新增防水工程，含底座區域防水及試水測試",
  },
  {
    id: "dep-008",
    severity: "critical",
    triggerKeywords: ["廚具拆除", "廚房拆除", "廚房全拆"],
    requiredKeywords: ["瓦斯管", "瓦斯封"],
    searchInCategories: ["plumbing"],
    title: "廚具拆除缺少瓦斯管封閉",
    why: "廚具拆除後瓦斯管若未封閉，有瓦斯外洩危險，屬安全問題",
    suggestion: "請新增瓦斯管封閉工項",
  },
  {
    id: "dep-009",
    severity: "critical",
    triggerKeywords: ["天花板拆除"],
    requiredKeywords: ["天花板", "平釘天花", "造型天花"],
    searchInCategories: ["carpentry"],
    title: "天花板拆除缺少天花板重做",
    why: "拆除天花板後不可能不做處理（除非刻意保留裸天花工業風格）",
    suggestion: "請新增天花板工程（平釘或造型天花板）",
  },
  {
    id: "dep-010",
    severity: "warning",
    triggerKeywords: ["隔間牆拆除", "隔間拆除"],
    requiredKeywords: ["結構", "結構確認", "結構補強"],
    title: "隔間牆拆除缺少結構確認",
    why: "需確認拆除的是否為結構牆，結構牆不可拆除，誤拆可能造成建築安全問題",
    suggestion: "請確認拆除牆面是否為結構牆，建議由結構技師確認",
  },
  {
    id: "dep-011",
    severity: "critical",
    triggerKeywords: ["馬桶移位"],
    requiredKeywords: ["墊高", "地板墊高", "架高"],
    searchInCategories: ["masonry", "plumbing", "flooring"],
    title: "馬桶移位缺少墊高地板",
    why: "馬桶移位需要糞管配管，排汙管需要洩水坡度，因此需墊高地板",
    suggestion: "請新增地板墊高工項",
  },
  {
    id: "dep-012",
    severity: "warning",
    triggerKeywords: ["全室拆除", "全面拆除"],
    requiredKeywords: ["保護工程", "電梯保護", "公共區域保護"],
    searchInCategories: ["protection"],
    title: "全室拆除缺少保護工程",
    why: "全室拆除工程量大，搬運廢料容易損壞公設，大樓施工幾乎必備保護工程",
    suggestion: "請新增保護工程（電梯保護+公共區域保護）",
  },
  {
    id: "dep-013",
    severity: "critical",
    triggerKeywords: ["空調安裝", "冷氣安裝", "冷氣"],
    requiredKeywords: ["排水管", "排水器", "冷凝水"],
    searchInCategories: ["hvac", "plumbing"],
    title: "空調安裝缺少排水管",
    why: "冷氣運作產生冷凝水，未配排水管會導致漏水",
    suggestion: "請新增冷氣排水管或排水器工項",
  },
  {
    id: "dep-014",
    severity: "info",
    triggerKeywords: ["系統櫃", "衣櫃", "書櫃"],
    requiredKeywords: ["丈量", "淨高", "確認淨高"],
    searchInCategories: ["cabinet"],
    title: "系統櫃提醒：需確認淨高",
    why: "系統櫃需在天花板完成後才丈量確認淨高，淨高確定才能下料生產",
    suggestion: "請確認系統櫃丈量時程安排在天花板完工後",
  },
  {
    id: "dep-015",
    severity: "warning",
    triggerKeywords: ["貼磁磚", "貼地磚", "貼壁磚"],
    requiredKeywords: ["收邊條", "收邊", "矽利康"],
    searchInCategories: ["masonry", "flooring"],
    title: "貼磁磚缺少收邊條",
    why: "磁磚與其他材質交接處需收邊處理，否則影響美觀及安全",
    suggestion: "請新增收邊條或矽利康收邊工項",
  },
];
