import type { TemplateItem } from "../types.js";

export const cabinetTemplates: TemplateItem[] = [
  {
    id: "tpl-cabinet-001",
    category: "cabinet",
    itemName: "系統衣櫃",
    unit: "尺",
    description: "含內部配件（層板、吊衣桿），需確認淨高",
    defaultIncludes: "櫃體、門片、基本層板、吊衣桿",
    defaultExcludes: "抽屜加購、拉籃、五金升級、櫃內電源",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "partial", "commercial", "retail", "restaurant", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 1,
  },
  {
    id: "tpl-cabinet-002",
    category: "cabinet",
    itemName: "玄關鞋櫃",
    unit: "尺",
    description: "玄關收納，常漏透氣孔設計",
    defaultIncludes: "櫃體、門片、層板",
    defaultExcludes: "透氣孔設計、五金升級",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "partial", "commercial", "retail", "restaurant", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 2,
  },
  {
    id: "tpl-cabinet-003",
    category: "cabinet",
    itemName: "系統廚具",
    unit: "組",
    description: "含上下櫃、檯面、水槽",
    defaultIncludes: "上櫃、下櫃、檯面、水槽、基本五金",
    defaultExcludes: "電器設備、瓦斯爐、排油煙機、拉籃等加購五金",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "commercial", "retail", "restaurant", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 3,
  },
  {
    id: "tpl-cabinet-004",
    category: "cabinet",
    itemName: "電器櫃",
    unit: "尺",
    description: "廚房電器收納，需散熱設計",
    defaultIncludes: "櫃體、層板",
    defaultExcludes: "散熱設計（拍拍門）、櫃內電源插座",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "partial", "commercial", "retail", "restaurant", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 4,
  },
];
