import type { TemplateItem } from "../types.js";

export const carpentryTemplates: TemplateItem[] = [
  {
    id: "tpl-carpentry-001",
    category: "carpentry",
    itemName: "平釘天花板",
    unit: "坪",
    description: "矽酸鈣板+輕鋼架/角材",
    defaultIncludes: "矽酸鈣板、輕鋼架或角材骨架、施工",
    defaultExcludes: "油漆工程、崁燈開孔、維修孔",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "commercial", "retail", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 1,
  },
  {
    id: "tpl-carpentry-002",
    category: "carpentry",
    itemName: "造型天花板",
    unit: "坪",
    description: "間接照明、弧形、多層次天花板",
    defaultIncludes: "造型骨架、矽酸鈣板、間接照明燈槽",
    defaultExcludes: "油漆工程、燈具、崁燈開孔",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "commercial", "retail", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 2,
  },
  {
    id: "tpl-carpentry-003",
    category: "carpentry",
    itemName: "窗簾盒",
    unit: "尺",
    description: "隱藏窗簾軌道，有裝窗簾時常漏",
    defaultIncludes: "窗簾盒木作施作",
    defaultExcludes: "油漆、窗簾軌道",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "partial", "commercial", "retail", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 3,
  },
  {
    id: "tpl-carpentry-004",
    category: "carpentry",
    itemName: "冷氣包管",
    unit: "尺",
    description: "隱藏冷媒管、排水管",
    defaultIncludes: "包管木作施作",
    defaultExcludes: "油漆",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "partial", "commercial", "retail", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 4,
  },
  {
    id: "tpl-carpentry-005",
    category: "carpentry",
    itemName: "木作隔間",
    unit: "坪",
    description: "含隔音棉施作",
    defaultIncludes: "雙面矽酸鈣板、骨架",
    defaultExcludes: "隔音棉（常另計）、油漆",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "commercial", "retail", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 5,
  },
  {
    id: "tpl-carpentry-006",
    category: "carpentry",
    itemName: "門框/門片",
    unit: "樘",
    description: "含五金（鉸鏈、把手、門鎖）",
    defaultIncludes: "門框、門片安裝",
    defaultExcludes: "五金配件（鉸鏈、把手、門鎖常另計）、油漆",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "commercial", "retail", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 6,
  },
];
