import type { TemplateItem } from "../types.js";

export const demolitionTemplates: TemplateItem[] = [
  {
    id: "tpl-demolition-001",
    category: "demolition",
    itemName: "天花板拆除",
    unit: "坪",
    description: "含輕鋼架、木作、矽酸鈣板拆除",
    defaultIncludes: "天花板面材拆除、骨架拆除",
    defaultExcludes: "垃圾清運、天花板重做",
    applicableTypes: ["mid_age", "old_renovation", "restaurant"],
    commonlyMissed: false,
    sortOrder: 1,
  },
  {
    id: "tpl-demolition-002",
    category: "demolition",
    itemName: "隔間牆拆除",
    unit: "面",
    description: "磚牆或輕隔間拆除，需確認是否為結構牆",
    defaultIncludes: "牆面拆除、地面牆根清除",
    defaultExcludes: "結構補強、地面修補、天花板修補、垃圾清運",
    applicableTypes: ["mid_age", "old_renovation", "restaurant"],
    commonlyMissed: false,
    sortOrder: 2,
  },
  {
    id: "tpl-demolition-003",
    category: "demolition",
    itemName: "地磚拆除（打見底）",
    unit: "坪",
    description: "含打底層，打見底，拆除後需整平及防水",
    defaultIncludes: "地磚及底層打除",
    defaultExcludes: "地面整平、防水工程、垃圾清運",
    applicableTypes: ["mid_age", "old_renovation", "restaurant"],
    commonlyMissed: false,
    sortOrder: 3,
  },
  {
    id: "tpl-demolition-004",
    category: "demolition",
    itemName: "壁磚拆除",
    unit: "坪",
    description: "浴室或廚房壁磚拆除",
    defaultIncludes: "壁磚及底層打除",
    defaultExcludes: "壁面粉光、重新貼磚、垃圾清運",
    applicableTypes: ["mid_age", "old_renovation", "restaurant"],
    commonlyMissed: false,
    sortOrder: 4,
  },
  {
    id: "tpl-demolition-005",
    category: "demolition",
    itemName: "衛浴設備拆除",
    unit: "間",
    description: "馬桶、面盆、浴缸等衛浴設備拆除",
    defaultIncludes: "馬桶、面盆拆除、管口封堵",
    defaultExcludes: "浴缸拆除、防水工程、垃圾清運",
    applicableTypes: ["mid_age", "old_renovation", "restaurant"],
    commonlyMissed: false,
    sortOrder: 5,
  },
  {
    id: "tpl-demolition-006",
    category: "demolition",
    itemName: "廚具拆除",
    unit: "式",
    description: "上下櫃、檯面、水槽拆除",
    defaultIncludes: "廚具上下櫃拆除、檯面拆除、水槽拆除",
    defaultExcludes: "瓦斯管封閉、水電管封管、垃圾清運",
    applicableTypes: ["mid_age", "old_renovation", "restaurant"],
    commonlyMissed: false,
    sortOrder: 6,
  },
  {
    id: "tpl-demolition-007",
    category: "demolition",
    itemName: "門窗拆除",
    unit: "樘",
    description: "含門框或窗框拆除",
    defaultIncludes: "門片或窗扇拆除、門框或窗框拆除",
    defaultExcludes: "泥作填縫修補、新門窗安裝、垃圾清運",
    applicableTypes: ["mid_age", "old_renovation", "restaurant"],
    commonlyMissed: false,
    sortOrder: 7,
  },
  {
    id: "tpl-demolition-008",
    category: "demolition",
    itemName: "垃圾清運",
    unit: "車",
    description: "拆除廢料清運，3.5噸車，最常被漏報的項目",
    defaultIncludes: "廢料裝袋、搬運至車上、清運處理",
    defaultExcludes: "樓層搬運加價（無電梯時）",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "partial", "commercial", "retail", "restaurant", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 8,
  },
  {
    id: "tpl-demolition-009",
    category: "demolition",
    itemName: "浴缸拆除",
    unit: "座",
    description: "浴缸拆除含底座打除",
    defaultIncludes: "浴缸體拆除、底座打除",
    defaultExcludes: "防水工程、垃圾清運、地面整平",
    applicableTypes: ["mid_age", "old_renovation", "restaurant"],
    commonlyMissed: false,
    sortOrder: 9,
  },
  {
    id: "tpl-demolition-010",
    category: "demolition",
    itemName: "木作裝潢拆除",
    unit: "坪",
    description: "既有木作裝潢拆除",
    defaultIncludes: "木作面材及骨架拆除",
    defaultExcludes: "垃圾清運、壁面修補",
    applicableTypes: ["mid_age", "old_renovation", "restaurant"],
    commonlyMissed: false,
    sortOrder: 10,
  },
];
