import type { TemplateItem } from "../types.js";

export const flooringTemplates: TemplateItem[] = [
  {
    id: "tpl-flooring-001",
    category: "flooring",
    itemName: "超耐磨木地板",
    unit: "坪",
    description: "卡扣式鋪設，經濟實惠耐刮",
    defaultIncludes: "地板材料、鋪設工資",
    defaultExcludes: "防潮布、收邊條、門檻條、自平水泥",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "partial", "commercial", "retail", "restaurant", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 1,
  },
  {
    id: "tpl-flooring-002",
    category: "flooring",
    itemName: "防潮布/防潮墊",
    unit: "坪",
    description: "木地板底層必備，台灣氣候潮濕強烈建議",
    defaultIncludes: "防潮布鋪設",
    defaultExcludes: "地板鋪設",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "partial", "commercial", "retail", "restaurant", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 2,
  },
  {
    id: "tpl-flooring-003",
    category: "flooring",
    itemName: "收邊條/踢腳板",
    unit: "尺",
    description: "地板與牆面交接收邊",
    defaultIncludes: "收邊條或踢腳板安裝",
    defaultExcludes: "矽利康收邊",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "partial", "commercial", "retail", "restaurant", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 3,
  },
  {
    id: "tpl-flooring-004",
    category: "flooring",
    itemName: "SPC石塑地板",
    unit: "坪",
    description: "防水，適合潮濕區域",
    defaultIncludes: "地板材料、鋪設工資",
    defaultExcludes: "收邊條、門檻條",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "partial", "commercial", "retail", "restaurant", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 4,
  },
];
