import type { TemplateItem } from "../types.js";

export const masonryTemplates: TemplateItem[] = [
  {
    id: "tpl-masonry-001",
    category: "masonry",
    itemName: "砌磚牆",
    unit: "坪",
    description: "1B(24cm)或半B(12cm)磚牆砌築",
    defaultIncludes: "紅磚、水泥砂漿、砌築工資",
    defaultExcludes: "粉光、油漆",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 1,
  },
  {
    id: "tpl-masonry-002",
    category: "masonry",
    itemName: "粉光",
    unit: "坪",
    description: "新砌牆面粉光，上漆前必須施作",
    defaultIncludes: "水泥砂漿粉光、表面整平",
    defaultExcludes: "油漆工程",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 2,
  },
  {
    id: "tpl-masonry-003",
    category: "masonry",
    itemName: "地面整平",
    unit: "坪",
    description: "拆除後地面高低差整平",
    defaultIncludes: "水泥砂漿打底整平",
    defaultExcludes: "自平水泥、防水工程",
    applicableTypes: ["mid_age", "old_renovation", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 3,
  },
  {
    id: "tpl-masonry-004",
    category: "masonry",
    itemName: "自平水泥",
    unit: "坪",
    description: "精密整平，木地板鋪設前施作",
    defaultIncludes: "自平水泥施作、養護",
    defaultExcludes: "地板鋪設",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 4,
  },
  {
    id: "tpl-masonry-005",
    category: "masonry",
    itemName: "貼地磚",
    unit: "坪",
    description: "含黏著劑、填縫",
    defaultIncludes: "磁磚鋪貼、黏著劑、填縫",
    defaultExcludes: "磁磚材料費、收邊條、門檻石",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 5,
  },
  {
    id: "tpl-masonry-006",
    category: "masonry",
    itemName: "洗洞/鑽孔",
    unit: "個",
    description: "冷氣、全熱交換器穿牆孔",
    defaultIncludes: "鑽孔施作、粉塵清理",
    defaultExcludes: "收邊處理（矽利康另計）",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "partial", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 6,
  },
  {
    id: "tpl-masonry-007",
    category: "masonry",
    itemName: "門檻石安裝",
    unit: "支",
    description: "浴室、房間門口、廚房門檻石",
    defaultIncludes: "門檻石安裝、水泥固定",
    defaultExcludes: "門檻石材料費",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 7,
  },
  {
    id: "tpl-masonry-008",
    category: "masonry",
    itemName: "貼壁磚",
    unit: "坪",
    description: "浴室、廚房壁面貼磚",
    defaultIncludes: "壁磚鋪貼、黏著劑、填縫",
    defaultExcludes: "磁磚材料費、收邊條",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 8,
  },
];
