import type { TemplateItem } from "../types.js";

export const paintingTemplates: TemplateItem[] = [
  {
    id: "tpl-painting-001",
    category: "painting",
    itemName: "批土（AB膠）",
    unit: "坪",
    description: "天花板及牆面不平處填補",
    defaultIncludes: "AB膠批土、表面整平研磨",
    defaultExcludes: "底漆、面漆",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "commercial", "retail", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 1,
  },
  {
    id: "tpl-painting-002",
    category: "painting",
    itemName: "底漆+面漆（乳膠漆）",
    unit: "坪",
    description: "含底漆1道+面漆2道，牆面及天花板",
    defaultIncludes: "底漆一道、面漆二道、含牆面及天花板",
    defaultExcludes: "批土、木作漆、特殊漆",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "partial", "commercial", "retail", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 2,
  },
  {
    id: "tpl-painting-003",
    category: "painting",
    itemName: "天花板油漆",
    unit: "坪",
    description: "天花板含批土+底漆+面漆，常只報牆面忘記天花",
    defaultIncludes: "天花板批土、底漆、面漆",
    defaultExcludes: "牆面油漆",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "commercial", "retail", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 3,
  },
  {
    id: "tpl-painting-004",
    category: "painting",
    itemName: "壁癌處理",
    unit: "坪",
    description: "刮除、防水、重新粉刷",
    defaultIncludes: "壁癌刮除、防水塗料施作、重新粉刷",
    defaultExcludes: "結構性防水處理",
    applicableTypes: ["old_renovation", "commercial", "retail", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 4,
  },
];
