import type { TemplateItem } from "../types.js";

export const plumbingTemplates: TemplateItem[] = [
  {
    id: "tpl-plumbing-001",
    category: "plumbing",
    itemName: "配電箱更換",
    unit: "式",
    description: "更換總開關箱及無熔絲開關",
    defaultIncludes: "配電箱體、無熔絲開關更換、標示",
    defaultExcludes: "漏電斷路器另計",
    applicableTypes: ["old_renovation", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 1,
  },
  {
    id: "tpl-plumbing-002",
    category: "plumbing",
    itemName: "電線更換/重拉",
    unit: "迴路",
    description: "電線壽命約9年，老屋建議全面更新",
    defaultIncludes: "電線抽換、迴路配線、開關箱內接線",
    defaultExcludes: "開關插座面板、配電箱更換",
    applicableTypes: ["mid_age", "old_renovation", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 2,
  },
  {
    id: "tpl-plumbing-003",
    category: "plumbing",
    itemName: "迴路增設",
    unit: "迴路",
    description: "廚房電器、冷氣需獨立迴路",
    defaultIncludes: "配管配線、開關箱內接線",
    defaultExcludes: "開關插座面板",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "partial", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 3,
  },
  {
    id: "tpl-plumbing-004",
    category: "plumbing",
    itemName: "開關插座新增/移位",
    unit: "組",
    description: "含配管配線",
    defaultIncludes: "暗管配線、出線口",
    defaultExcludes: "開關插座面板費用",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "partial", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 4,
  },
  {
    id: "tpl-plumbing-005",
    category: "plumbing",
    itemName: "弱電配線（網路）",
    unit: "點",
    description: "網路線配管配線",
    defaultIncludes: "Cat6網路線、PVC配管、出線口",
    defaultExcludes: "網路設備、面板",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 5,
  },
  {
    id: "tpl-plumbing-006",
    category: "plumbing",
    itemName: "給水管更換",
    unit: "式",
    description: "冷熱水管更換，老屋建議全面更新",
    defaultIncludes: "冷水管(PVC)、熱水管(不鏽鋼壓接管)更換",
    defaultExcludes: "壓力測試、泥作封管修補",
    applicableTypes: ["mid_age", "old_renovation", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 6,
  },
  {
    id: "tpl-plumbing-007",
    category: "plumbing",
    itemName: "排水管更換",
    unit: "式",
    description: "PVC排水管更換",
    defaultIncludes: "排水管配管、接頭",
    defaultExcludes: "泥作封管修補",
    applicableTypes: ["mid_age", "old_renovation", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 7,
  },
  {
    id: "tpl-plumbing-008",
    category: "plumbing",
    itemName: "糞管移位",
    unit: "式",
    description: "馬桶位置變更時需要，需配合墊高地板",
    defaultIncludes: "糞管配管、接頭",
    defaultExcludes: "地板墊高、泥作修補",
    applicableTypes: ["mid_age", "old_renovation", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 8,
  },
  {
    id: "tpl-plumbing-009",
    category: "plumbing",
    itemName: "瓦斯管封閉/檢查",
    unit: "式",
    description: "廚具拆除後瓦斯管安全封閉",
    defaultIncludes: "瓦斯管封堵、安全確認",
    defaultExcludes: "瓦斯管重新配管",
    applicableTypes: ["mid_age", "old_renovation", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 9,
  },
  {
    id: "tpl-plumbing-010",
    category: "plumbing",
    itemName: "接地線",
    unit: "式",
    description: "安全規範要求，老屋常缺",
    defaultIncludes: "接地線配置",
    defaultExcludes: "配電箱更換",
    applicableTypes: ["old_renovation", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: true,
    sortOrder: 10,
  },
  {
    id: "tpl-plumbing-011",
    category: "plumbing",
    itemName: "浴室抽風機配線",
    unit: "台",
    description: "含配電配管",
    defaultIncludes: "電源配線、控制開關配線",
    defaultExcludes: "抽風機設備",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 11,
  },
  {
    id: "tpl-plumbing-012",
    category: "plumbing",
    itemName: "對講機/門鈴配線",
    unit: "式",
    description: "含配線及移位",
    defaultIncludes: "對講機配線、移位工程",
    defaultExcludes: "對講機設備",
    applicableTypes: ["mid_age", "old_renovation", "commercial", "restaurant", "raw", "office"],
    commonlyMissed: false,
    sortOrder: 12,
  },
];
