import type { TemplateItem } from "../types.js";

export const protectionTemplates: TemplateItem[] = [
  {
    id: "tpl-protection-001",
    category: "protection",
    itemName: "電梯保護",
    unit: "式",
    description: "大樓施工必備，電梯內壁鋪設保護板，防止建材搬運刮傷",
    defaultIncludes: "電梯內壁保護板鋪設、防撞泡棉",
    defaultExcludes: "保護材料拆除清運",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "partial"],
    commonlyMissed: true,
    sortOrder: 1,
  },
  {
    id: "tpl-protection-002",
    category: "protection",
    itemName: "公共區域保護",
    unit: "式",
    description: "走廊、樓梯間鋪設保護板，含牆面保護",
    defaultIncludes: "走道地面保護板、牆面保護板鋪設",
    defaultExcludes: "保護材料拆除清運",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "partial"],
    commonlyMissed: true,
    sortOrder: 2,
  },
  {
    id: "tpl-protection-003",
    category: "protection",
    itemName: "室內地板保護",
    unit: "坪",
    description: "保留區域地板鋪設PVC防護板或防潮布",
    defaultIncludes: "PVC保護板或防潮布鋪設",
    defaultExcludes: "保護材料拆除清運",
    applicableTypes: ["new_build", "mid_age", "old_renovation", "partial"],
    commonlyMissed: false,
    sortOrder: 3,
  },
  {
    id: "tpl-protection-004",
    category: "protection",
    itemName: "門框保護",
    unit: "式",
    description: "泡棉包覆門框，防止施工碰撞損傷",
    defaultIncludes: "泡棉包覆門框",
    defaultExcludes: "門框修復",
    applicableTypes: ["mid_age", "old_renovation", "partial"],
    commonlyMissed: false,
    sortOrder: 4,
  },
];
